- name: Install dependencies
  run: npm install
- name: Run script
  run: node index.js
  env:
    CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
    CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
